### ISSUE TITLE
Intent to change to specific channel while in an activity (Watch TV)

### ISSUE THREAD

**Issue by dubsquared** [sushilks/alexaHarmonyApp#4]
I've tried to use the volume intent as guide to figure out how to write an intent to change to a specific channel.  The available commands are NumericBasic and Channel, Channel Up and Channel, Channel Down.  Using those, I figure I can get a "decrease channel by 2" command to work, but that's not what I'm looking for.  Can you provide some guidance on how to write an intent to change to a specific channel?  

```
app.intent('ChangeChannel',
    {
        "slots" : {'AMOUNT' : 'NUMBER'},
        "utterances" : ["change|} channel {to|} {1-1000|AMOUNT}"]
    },
    function (req, res) {
    var amt=parseInt(req.slot('AMOUNT'), 10);
    if (isNaN(amt)) {
           amt = 1;
    }
    res.say('Changing channel to ' + amt);
    console.log('Changing channel to ' + amt);
    execCmdCurrentActivity('NumericBasic, 5', amt, function (res) {
        console.log("Command Change Channel was executed with result : " + res);
    });
});
```

**Comment by sushilks** [comment]
there is a "{" missing in the utterance definition 
"utterances" : ["{change|} channel {to|} {1-1000|AMOUNT}"]
beside that what you have seems fine to me, are you facing any issue with the above code ?

To get the exact arguments to pass on to the function's  "execCmdCurrentActivity" or "execCmd"
you can use the "harmonyHubCLI" in read mode in your network. It will show you all the available commands for the specific device or for Activity that you have programmed on the remote.

It's best to use the CLI to check if "NumericBasic" will work on your setup to change the channel or if something else is needed. 

Since I have not tried this would be nice to know what you find, Post back what worked.

**Comment by dubsquared** [comment]
Thanks for the lint check on the utterance definition!  I've updated my file, but the issue still persists.

Using the hubCLI, I have verified that"NumericBasic,{1-9} are available commands while in the 'Watch TV' activity.  Using the code above I can change to any single digit channel {1-9}, but no channels that require two inputs.  Is there a way to chain two commands together?  If I want channel 24, I likely need to issue "NumericBasic,2" + "NumericBasic,4"

**Comment by sushilks** [comment]
if you run two commands back to back as you indicated "NumericBasic,2" +
"NumericBasic,4", I don't see any reason for it to not work.
If it does not try putting some delay between the commands.

**Comment by AppleTechy** [comment]
@sushilks Can you take a look at sushilks/harmonyHubCLI#4 ? I had a a similiar on how I would link a command together for a channel number. Would appreciate any guidance!

**Comment by sushilks** [comment]
With the latest version supporting multiple commands this should work, 
have a look at readme for details.

Specifically Try:
node harmonyHubCLI.js -a 'Watch TV' -c '["NumericBasic,2","NumericBasic,4"]' -m

I will close this for now, feel free to ping back if you are seeing any more problems.
